GET http://localhost:3000/services
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWMxNDg5NjNiMDczMWI3NjdmNjU4MWQiLCJpYXQiOjE3OTEwNTcyMTUsImV4cCI6MTc5ODgzMzIxNX0.nx_Tqrqd7RbcdyDkfEvhtHTKLXQhv_TuSvIYQ_JUG3E

